on:
  push:
    tags:
      - "v*"

env:
  appname: blinker

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: "25"

      - name: Install application dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Audit
        run: npm audit

      - name: Install Tauri dependencies (debian)
        run: |
          apt-get update
          apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Build application
        run: |
          npm run tauri build
      
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: ${{ env.appname }}.flatpak
          manifest-path: org.blinker.Blinker.yaml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Create the binary archive
        run: tar -c --xz -f ${{ env.appname }}.tar.xz ./src-tauri/target/release/${{ env.appname }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7
        id: upload-artifact
        with:
          name: linux-packages
          path: |
            ./${{ env.appname }}.flatpak
            ./${{ env.appname }}.tar.xz
            ./src-tauri/target/release/bundle/appimage/${{ env.appname }}.AppImage
            ./src-tauri/target/release/bundle/rpm/${{ env.appname }}*.rpm
            ./src-tauri/target/release/bundle/deb/${{ env.appname }}*.deb

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: linux-packages
          subject-digest: sha256:${{ steps.upload-artifact.outputs.artifact-digest }}

  release:
    runs-on: ubuntu-slim
    needs:
      - build
    permissions:
      contents: write
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v8
        id: download-artifact
        with:
          name: linux-packages

      - name: GH Release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ steps.download-artifact.outputs.download-path }}/*
